import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../utils/utils";
import { Header } from "./_components/Header";
import type { Viewport } from "next";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "")}>
        <div className="flex">
          <div className="bg-myYellow-base">
            <Header
              headerColor="bg-myYellow-base"
              logoColor="text-myPurple-base"
            />
            <Home primaryColor="bg-myPurple-base" />
          </div>
          <div className="bg-white">
            <Header headerColor="bg-white" logoColor="text-blue-primary" />
            <Home
              primaryColor="bg-blue-primary"
              secondaryColor="bg-blue-secondary"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
