import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "../utils/utils";
import { Header } from "./_components/Header";
import type { Viewport } from "next";
import { PHProvider } from "./providers/providers";
import dynamic from "next/dynamic";
import { Footer } from "@/components/ui/Footer";
const PostHogPageView = dynamic(() => import("./PostHogPageView"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });
const sans = DM_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PHProvider>
        <body
          className={cn(
            sans.className,
            "bg-gradient-to-b from-backgroundGradient-start to-backgroundGradient-end"
          )}
        >
          <PostHogPageView />
          <Header />
          {children}
          <Footer />
        </body>
      </PHProvider>
    </html>
  );
}
